- name: Update apt cache
  become: yes
  apt:
    update_cache: yes

- name: Install common packages
  apt:
    name:
      - unzip
      - socat
      - htop
      - net-tools
    state: present

- name: Download redirector software
  ansible.builtin.get_url:
    url: https://github.com/D00Movenok/BounceBack/releases/download/v1.5.1/BounceBack_1.5.1_linux_amd64.zip
    dest: /home/{{ ansible_user }}/bounceback.zip
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Unzip redirector software
  ansible.builtin.unarchive:
    src: "/home/{{ ansible_user }}/bounceback.zip"
    dest: "/home/{{ ansible_user }}/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    remote_src: true


# https://github.com/ansible/ansible-modules-core/issues/5744
# - name: Fix permissions of home directory
#   file:
#     path: "/home/{{ ansible_user }}/"
#     owner: "{{ ansible_user }}"
#     group: "{{ ansible_user }}"
#     recurse: yes

# Disable to allow DNS proxy
# - name: Stop service systemd-resolved, if started
#   #ansible.builtin.systemd_service:
#   ansible.builtin.systemd:
#     name: systemd-resolved
#     state: stopped
#     enabled: false
#     force: true
# sudo systemctl stop systemd-resolved
# sudo systemctl disable systemd-resolved
# if needed restart:
# sudo systemctl restart systemd-resolved